#define TRLSL_T_IDENTIFIER                       1
#define TRLSL_T_INTCONSTANT                      2
#define TRLSL_T_UINTCONSTANT                     3
#define TRLSL_T_FLOATCONSTANT                    4
#define TRLSL_T_BOOLCONSTANT                     5
#define TRLSL_T_LS                               6
#define TRLSL_T_RS                               7
#define TRLSL_T_LM                               8
#define TRLSL_T_RM                               9
#define TRLSL_T_DOT                             10
#define TRLSL_T_FIELD_SELECTION                 11
#define TRLSL_T_INC_OP                          12
#define TRLSL_T_DEC_OP                          13
#define TRLSL_T_VOID                            14
#define TRLSL_T_COMMA                           15
#define TRLSL_T_PLUS                            16
#define TRLSL_T_DASH                            17
#define TRLSL_T_BANG                            18
#define TRLSL_T_TILDE                           19
#define TRLSL_T_STAR                            20
#define TRLSL_T_SLASH                           21
#define TRLSL_T_PERCENT                         22
#define TRLSL_T_LEFT_OP                         23
#define TRLSL_T_RIGHT_OP                        24
#define TRLSL_T_LEFT_ANGLE                      25
#define TRLSL_T_RIGHT_ANGLE                     26
#define TRLSL_T_LE_OP                           27
#define TRLSL_T_GE_OP                           28
#define TRLSL_T_EQ_OP                           29
#define TRLSL_T_NE_OP                           30
#define TRLSL_T_AMPERSAND                       31
#define TRLSL_T_CARET                           32
#define TRLSL_T_VERTICAL_BAR                    33
#define TRLSL_T_AND_OP                          34
#define TRLSL_T_OR_OP                           35
#define TRLSL_T_QUESTION                        36
#define TRLSL_T_COLON                           37
#define TRLSL_T_EQUAL                           38
#define TRLSL_T_MUL_ASSIGN                      39
#define TRLSL_T_DIV_ASSIGN                      40
#define TRLSL_T_MOD_ASSIGN                      41
#define TRLSL_T_ADD_ASSIGN                      42
#define TRLSL_T_SUB_ASSIGN                      43
#define TRLSL_T_LEFT_ASSIGN                     44
#define TRLSL_T_RIGHT_ASSIGN                    45
#define TRLSL_T_AND_ASSIGN                      46
#define TRLSL_T_XOR_ASSIGN                      47
#define TRLSL_T_OR_ASSIGN                       48
#define TRLSL_T_SEMICOLON                       49
#define TRLSL_T_CONST                           50
#define TRLSL_T_IN                              51
#define TRLSL_T_OUT                             52
#define TRLSL_T_INOUT                           53
#define TRLSL_T_UNIFORM                         54
#define TRLSL_T_STRUCT                          55
#define TRLSL_T_FLOAT                           56
#define TRLSL_T_INT                             57
#define TRLSL_T_UINT                            58
#define TRLSL_T_BOOL                            59
#define TRLSL_T_VEC2                            60
#define TRLSL_T_VEC3                            61
#define TRLSL_T_VEC4                            62
#define TRLSL_T_BVEC2                           63
#define TRLSL_T_BVEC3                           64
#define TRLSL_T_BVEC4                           65
#define TRLSL_T_IVEC2                           66
#define TRLSL_T_IVEC3                           67
#define TRLSL_T_IVEC4                           68
#define TRLSL_T_UVEC2                           69
#define TRLSL_T_UVEC3                           70
#define TRLSL_T_UVEC4                           71
#define TRLSL_T_MAT2                            72
#define TRLSL_T_MAT3                            73
#define TRLSL_T_MAT4                            74
#define TRLSL_T_MAT2X2                          75
#define TRLSL_T_MAT2X3                          76
#define TRLSL_T_MAT2X4                          77
#define TRLSL_T_MAT3X2                          78
#define TRLSL_T_MAT3X3                          79
#define TRLSL_T_MAT3X4                          80
#define TRLSL_T_MAT4X2                          81
#define TRLSL_T_MAT4X3                          82
#define TRLSL_T_MAT4X4                          83
#define TRLSL_T_SAMPLER2D                       84
#define TRLSL_T_SAMPLER3D                       85
#define TRLSL_T_SAMPLERCUBE                     86
#define TRLSL_T_HIGH_PRECISION                  87
#define TRLSL_T_MEDIUM_PRECISION                88
#define TRLSL_T_LOW_PRECISION                   89
#define TRLSL_T_LB                              90
#define TRLSL_T_RB                              91
#define TRLSL_T_IF                              92
#define TRLSL_T_ELSE                            93
#define TRLSL_T_WHILE                           94
#define TRLSL_T_FOR                             95
#define TRLSL_T_CONTINUE                        96
#define TRLSL_T_BREAK                           97
#define TRLSL_T_RETURN                          98
#define TRLSL_T_DISCARD                         99
#define TRLSL_T___EMPTY                         250 
#define TRLSL_T___LAST                          251 
